config/routes.rb
Groggr::Application.routes.draw do
  
  root :to => 'drinks#index'
  
  resources :items

  resources :drinks do
    resources :recipes
  end

end

app/models/drink.rb
class Drink < ActiveRecord::Base
  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :drink
  has_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  # GET /drinks
  # GET /drinks.json
  def index
    @drinks = Drink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drinks }
    end
  end

  # GET /drinks/1
  # GET /drinks/1.json
  def show
    @drink = Drink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @drink }
    end
  end

  # GET /drinks/new
  # GET /drinks/new.json
  def new
    @drink = Drink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @drink }
    end
  end

  # GET /drinks/1/edit
  def edit
    @drink = Drink.find(params[:id])
  end

  # POST /drinks
  # POST /drinks.json
  def create
    @drink = Drink.new(params[:drink])

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render json: @drink, status: :created, location: @drink }
      else
        format.html { render action: "new" }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drinks/1
  # PUT /drinks/1.json
  def update
    @drink = Drink.find(params[:id])

    respond_to do |format|
      if @drink.update_attributes(params[:drink])
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drinks/1
  # DELETE /drinks/1.json
  def destroy
    @drink = Drink.find(params[:id])
    @drink.destroy

    respond_to do |format|
      format.html { redirect_to drinks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :get_recipe
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :get_drink
  
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = @drink.recipes.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = @drink.recipes.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = @drink.recipes.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = @drink.recipes.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = @drink.recipes.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to edit_drink_path(@drink), notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = @drink.recipes.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to edit_drink_path(@drink), notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = @drink.recipes.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to drink_recipes_url @drink }
      format.json { head :no_content }
    end
  end
  
  private
  
  def get_drink
    @drink = Drink.find(params[:drink_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/drinks/_form.html.erb
<%= form_for(@drink) do |f| %>
  <% if @drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

      <ul>
      <% @drink.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Editing drink</h1>

<%= render 'form' %>

<ul>
<% @drink.recipes.each do |r| %>
	<li><%= r.description %> <%= link_to 'Redigera', edit_drink_recipe_path(@drink, r) %></li>
<% end %>
</ul>

<%= link_to 'Lägg till recept', new_drink_recipe_path(@drink) %>

<%= link_to 'Show', @drink %> |
<%= link_to 'Back', drinks_path %>

app/views/drinks/index.html.erb
<h1>Listing drinks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drinks.each do |drink| %>
  <tr>
    <td><%= drink.name %></td>
    <td><%= drink.description %></td>
    <td><%= link_to 'Show', drink %></td>
    <td><%= link_to 'Edit', edit_drink_path(drink) %></td>
    <td><%= link_to 'Destroy', drink, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Drink', new_drink_path %>

app/views/drinks/new.html.erb
<h1>New drink</h1>

<%= render 'form' %>

<%= link_to 'Back', drinks_path %>

app/views/drinks/show.html.haml
%section#drink.span7
  .img-container
    = image_tag("/images/sidecar-cocktail-recipe.jpeg", :alt => "rss feed")

  %h1.drink-title= @drink.name

  .tag-container Taggar och skit

  %p.description= @drink.description

  %p.controls
    = link_to t('edit'), edit_drink_path(@drink)
    = link_to t('back'), drinks_path

%aside#recipes.span5
  .swiper-container
    .swiper-wrapper
      - @drink.recipes.each do |r|
        %article.recipe.swiper-slide
          %header
            %h1.recipe-title= r.description

          .recipe-content
            .ingredients
              %h2= t('ingredients')
              %ul
                - r.ingredients.each do |ingredient|
                  %li
                    %span.amount= ingredient.amount
                    %span.unit= ingredient.unit
                    %span.name= ingredient.item.name

            .instructions 
              %h2= t('instructions')
              = r.instruction

          %footer
            %p= t('meta')

  %footer.controls
    = link_to t('next'), drink_path(@drink, anchor: 'next'), id: 'next-receipt'
    = link_to t('previous'), drink_path(@drink, anchor: 'prev'), id: 'prev-receipt'
    

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sb_article_number %><br />
    <%= f.text_field :sb_article_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Sb article number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= item.sb_article_number %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Sb article number:</b>
  <%= @item.sb_article_number %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.haml
!!! 5
!= '<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->'
!= '<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->'
!= '<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->'
!= '<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->'

%head
	%meta{'charset' => 'utf-8'}
	%meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}
	%title
		- if !@head_title.blank?
			= @head_title
			|
		groggr
	%meta{:name => 'description'}
	%meta{:name => 'author'}
	%meta{:name => 'viewport', :content => 'width=device-width,initial-scale=1'}
	
	= stylesheet_link_tag "application", :media => "all"
	= javascript_include_tag :header_scripts
	= csrf_meta_tags

%body
	#container
		%header#header.cf
			%h1.site-title groggr
			= yield :header
			= render 'partials/main_navigation'

		%section#main.cf.row-fluid
			= yield
		
		%footer#footer.cf
			= yield :footer
	
	= javascript_include_tag :footer_scripts
	
	:javascript
		var _gaq=[['_setAccount','UA-30615064-1'],['_trackPageview'],['_trackPageLoadTime']];
		(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
		g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
		s.parentNode.insertBefore(g,s)}(document,'script'));
		
!= '</html>'

app/views/partials/_main_navigation.html.haml
#menu-container.cf
	%ul.cf
		%li Hem
		%li Brandy
		%li Gin
		%li Rom

%a#menu-toggle{:href => '#toggle'}= t('show')

app/views/recipes/_form.html.haml
= form_for([@drink, @recipe]) do |f|
	- if @recipe.errors.any?
		#error-explanation
			%h2= pluralize(@recipe.errors.count, 'error') + t('prohibited this recipe from being saved') + ':'
			
			%ul
				- @recipe.errors.full_messages.each do |msg|
					%li= msg
	
	.field
		= f.label :description, t('description')
		%br
		= f.text_field :description
	
	.field
		= f.label :instruction, t('instructions')
		%br
		= f.text_area :instruction
	
	.actions= f.submit

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', drink_recipe_path(@recipe) %> |
<%= link_to 'Back', drink_recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Instruction</th>
    <th>Drink</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.description %></td>
    <td><%= recipe.instruction %></td>
    <td><%= recipe.drink %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @recipe.description %>
</p>

<p>
  <b>Instruction:</b>
  <%= @recipe.instruction %>
</p>

<p>
  <b>Drink:</b>
  <%= @recipe.drink %>
</p>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>